### ISSUE TITLE
Cannot compile on Kernel >= 6.11, because drm_fbdev_generic.h had been removed  in the linux headers. How to compile on 6.14 kernel header?

### ISSUE THREAD

**Issue by Zillaaa** [klogg/fl2000_drm#80]
I try to compile the actual code on ubuntu with kernel 6.14 but become this failure:
`warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  fl2000_drv.o
In file included from fl2000_drv.c:7:
fl2000.h:33:10: fatal error: drm/drm_fbdev_generic.h: Datei oder Verzeichnis nicht gefunden
   33 | #include <drm/drm_fbdev_generic.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

Google tells me that the header drm_fbdev_generic.h had been removed from Kernel 6.11, because drm_fbdev_generic_setup had been replaced by drm_fbdev_ttm_setup. 

How can i compile now on ubuntu with kernel > 6.11? (actual 6.14)
