### PR TITLE
Fix compatibility with Linux kernel 6.17

### PR DESCRIPTION
**Pull request by MatiZappacosta**
- Replace drm_fbdev_generic.h with drm_fbdev_shmem.h
- Remove deprecated .lastclose and .date from drm_driver
- Add DRM_FBDEV_SHMEM_DRIVER_OPS macro
- Update bridge_attach signature (add encoder parameter)
- Update mode_valid signature (add const)
- Migrate from struct edid to struct drm_edid API:
  - drm_do_get_edid -> drm_edid_read_custom
  - drm_connector_update_edid_property -> drm_edid_connector_update
  - drm_detect_hdmi_monitor -> drm_edid_is_digital
  - drm_add_edid_modes -> drm_edid_connector_add_modes
  - kfree -> drm_edid_free

Tested on Ubuntu 24.04 with kernel 6.17.0-14-generic

### CODE REVIEW

**Comment by ftoledo-opensa** [comment]
I can build on 6.12 (debian 13)
```
ragnarok@ragnarok-pc:~/src/fl2000_drm-mati$ make
make CHECK="/usr/bin/sparse" -C /lib/modules/6.12.74+deb13+1-amd64/build M=/home/ragnarok/src/fl2000_drm-mati modules
make[1]: se entra en el directorio '/usr/src/linux-headers-6.12.74+deb13+1-amd64'
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_drv.o
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_registers.o
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_interrupt.o
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_streaming.o
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_i2c.o
  CC [M]  /home/ragnarok/src/fl2000_drm-mati/fl2000_drm.o
/home/ragnarok/src/fl2000_drm-mati/fl2000_drm.c:112:9: error: ‘DRM_FBDEV_SHMEM_DRIVER_OPS’ undeclared here (not in a function); did you mean ‘DRM_GEM_DMA_DRIVER_OPS’?
  112 |         DRM_FBDEV_SHMEM_DRIVER_OPS,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         DRM_GEM_DMA_DRIVER_OPS
make[3]: *** [/usr/src/linux-headers-6.12.74+deb13+1-common/scripts/Makefile.build:234: /home/ragnarok/src/fl2000_drm-mati/fl2000_drm.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.12.74+deb13+1-common/Makefile:1970: /home/ragnarok/src/fl2000_drm-mati] Error 2
make[1]: *** [/usr/src/linux-headers-6.12.74+deb13+1-common/Makefile:236: __sub-make] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-6.12.74+deb13+1-amd64'
make: *** [Makefile:22: modules] Error 2
```
